server:
  port: ${PORT:8081}

spring:
  application:
    name: gateway-matematica
  cloud:
    gateway:
      routes:
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/usuario/**
          filters:
            - StripPrefix=1
        - id: questao
          uri: lb://questao
          predicates:
            - Path=/questao/**
          filters:
            - StripPrefix=1
        - id: resposta
          uri: lb://resposta
          predicates:
            - Path=/resposta/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://app-matematica-eureka-f69602e28e4d.herokuapp.com/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: app-matematica-gateway-a356f607c624.herokuapp.com
    non-secure-port: 80
    secure-port: 443
    prefer-ip-address: false

CHAVE_ASSINATURA_JWT: ${CHAVE_ASSINATURA_JWT}